version: '3'

services:
  backend:
    build:
      context: backend

    container_name: backend
    expose:
      - 5000
    ports:
      - 5000:5000

  gui:
    build:
      context: gui

    container_name: gui
    expose:
      - 3000
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
